// put here syscall code
.global syscall_puts
syscall_puts:
        // TODO
        ret

.global syscall_getpid
syscall_getpid:
        // TODO
        ret

.global syscall_fork
syscall_fork:
        // TODO
        ret

.global syscall_wait
syscall_wait:
        // TODO
        ret

.global syscall_exit
syscall_exit:
        // TODO
        ret

.global syscall_read
syscall_read:
        // TODO
        ret

.global syscall_exec
syscall_exec:
        // TODO
        ret
